### ISSUE TITLE
关于WaitForEvent事件的设计

### ISSUE THREAD

**Issue by tiansongyu** [UnknownBugs/TUGUI#29]
现在有键盘、鼠标等事件，目前对键盘事件的处理方式是单独设计一个waitforkeyEvent接口，这是因为从用户接口无法传输&(ST->ConIn->WaitForKey)这个数据结构。  
以后可以在抽象层设计一个宏，用来表示waitforevent的类型，比如键盘事件使用KEYBOARD_EVENT，这个数据最终在wrapper中的static unsinged long long waitforevent被解释成相应的&(__mST->ConIn->WaitForKey)  
通过添加在waitforevent添加一个参数，最终实现不同事件的抽象  
待实现后，关闭此issue

**Comment by Sunrisepeak** [comment]
to UEFIWrapper
